
name: Benchmark

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rinha
      run: |
        ${{ github.workspace }}/build.sh
        time build/rinha run benchmark/fib.json

    - name: Python3
      run: |
        python3 --version
        time python3 benchmark/fib.py
